package com.bloodbank.ui.model;

import java.time.LocalDate;

/**
 * Client-side model for a blood inventory batch.
 * batchCode is the unique identifier (e.g. BB-AP-20260512-42).
 * donorId links back to the donor who gave this blood.
 */
public class BloodInventory {
    public Long    id;
    public String  bloodGroup;
    public int     quantity;
    public LocalDate expiryDate;
    public LocalDate addedDate;
    public String  source;
    /** Unique batch code — generated by the server on creation */
    public String  batchCode;
    /** Donor who gave this blood (null for externally sourced stock) */
    public Long    donorId;

    public boolean isExpired() {
        return expiryDate != null && expiryDate.isBefore(LocalDate.now());
    }

    public boolean isExpiringSoon() {
        return expiryDate != null && !isExpired()
                && expiryDate.isBefore(LocalDate.now().plusDays(7));
    }

    /** Display label for the batch code column */
    public String getBatchCodeDisplay() {
        return batchCode != null ? batchCode : "—";
    }
}
